#!/usr/bin/env bash

text_red="$(tput setaf 1)"
text_bold="$(tput bold)"
text_reset="$(tput sgr0)"

declare -r text_reset
declare -r text_bold
declare -r text_red
declare -r line="_________________________________________"

echo -e "${line}\n"
echo "${text_red}${text_bold}Storage:${text_reset}"
echo "Filesystem      Size  Used Avail Use% Mounted on"
#df -h | grep {device path}
df -h | grep /dev/sda2 
echo -e "${line}\n"
echo "${text_red}${text_bold}Webserver online?${text_reset}"
systemctl status apache2.service | grep 'Active:' | sed 's/^[ \t]*//'
echo -e "${line}\n"

# more to come 
